spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/authenticate/**
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/user/**
server:
  port: 8082
eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost