spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/authenticate/**
        - id: UserEspace
          uri: lb://UserEspace
          predicates:
            - Path=/user/**
            - Path=/formulaire/**
server:
  port: 8082
eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: ${Eureka_Url}
  instance:
    hostname: ${hostname}