spring:
  application:
    name: RC_GatewayService
  cloud:
    gateway:
      routes:
        - id: RCAuthenticationService
          uri: lb://RCAuthenticationService
          predicates:
            - Path=/authenticate/**
        - id: RCUserEspace
          uri: lb://RCUserEspace
          predicates:
            - Path=/user/**
            - Path=/formulaire/**
server:
  port: 8092
eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: ${Eureka_Url}
  instance:
    hostname: ${hostname}