services:
  registry_service:
    container_name: "RC_Eureka"
    build: ./Backend/RegistryService
    hostname: eureka
    environment:
      hostname : "eureka"
    ports:
      - "8762:8761"
    networks:
      - RC_Network
  gateway_service:
    container_name: "RC_Gateway"
    build: ./Backend/GatewayService
    env_file: .env
    ports:
      - "8092:8082"
    networks:
      - RC_Network
    depends_on:
      - registry_service
      - authentication_service
  authentication_service:
    container_name: "RC_Auth"
    build: ./Backend/AuthenticationService
    env_file: .env
    ports:
      - "8093:8083"
    networks:
      - RC_Network
    depends_on:
      - registry_service
      - db
  db:
    container_name: "RCDB"
    image: "postgres:17-alpine"
    environment:
      POSTGRES_USERNAME : ${DB_Username}
      POSTGRES_PASSWORD : ${DB_Password}
      POSTGRES_DB : ${DB_Name}
    ports:
      - "5433:5432"
    volumes:
      - RC_Volume:/var/lib/postgresql/data
    networks:
      - RC_Network

volumes:
  RC_Volume:
    driver: local
networks:
  RC_Network:
    driver: bridge



