spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/authenticate/**
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/user/**
        - id: GeographyService
          uri: lb://GeographyService
          predicates:
            - Path=/geography/**
        - id : DemandsService
          uri: lb://DemandsService
          predicates:
            - Path=/demands/**
server:
  port: 8082
eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: ${Eureka_Url:http://localhost:8761/eureka/}
  instance:
    hostname: ${hostname:localhost}